# Generated by Django 5.0.2 on 2024-03-08 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_variation_variation_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('ram/rom', 'ram/rom')], max_length=20),
        ),
    ]
