# Generated by Django 5.0.2 on 2024-03-08 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_rename_variation_cartitem_variations'),
        ('store', '0007_specification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='variations',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='spec',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='store.specification'),
        ),
    ]
