# Generated by Django 5.0.2 on 2024-03-21 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='spec',
        ),
    ]
